name: Generate output

on:
  workflow_dispatch
      
jobs:
  generateOutput:
  
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Run Deno
        run: deno task generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: generate output
          title: Generate output
          body: Generate output
          branch: output
